# Generated by Django 4.2 on 2025-12-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailCheckRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_content", models.TextField()),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "prediction",
                    models.CharField(
                        choices=[("spam", "SPAM"), ("ham", "No es SPAM")], max_length=10
                    ),
                ),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Email Check Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
